  
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 3333
spring:
  application:
    name: Open-Data-Api

  boot:
    admin:
      client:
        url: "http://localhost:1111/"
  sleuth:
    trace-id128: true
    supports-join: false   
    
#  spring.cloud.compatibility-verifier.enabled=fals
  cloud:
    compatibility-verifier:
      enabled: false
